# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 258ebdb972513b47ad3d3aad88ef603dcf595f1b9d9928c24eb5d24d2269fe093fb3ac9c4fa1352d2c1eab48a180c284d459c96880b1ce72020aa03159bcedf3

test:
  secret_key_base: fb2e9ece5bb92a9f008186c2a7d674af9dbe335528c2861e794adeb65cd0868ce694973ba3c96e12e6f9b085e0551831b6044d811a363e77fc943968db35742a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
